### ISSUE TITLE
 VM Quota issue

### ISSUE THREAD

**Issue by srkasuMsft** [swmannepalli/AzureSynapseAnalyticsWorkshop#8]
Getting VM Quota issue when validating the deployment template after filling in the company name. See error details below

{"code":"MultipleErrorsOccurred","details":[{"code":"InvalidTemplateDeployment","message":"The template deployment failed with error: 'The resource with id: '/subscriptions/2be16060-ff3f-43b7-90b2-9f5c7b76d746/resourceGroups/synapseworkshop/providers/Microsoft.Compute/virtualMachines/sricontoso-SQL' failed validation with message: 'The requested size for resource '/subscriptions/2be16060-ff3f-43b7-90b2-9f5c7b76d746/resourceGroups/synapseworkshop/providers/Microsoft.Compute/virtualMachines/sricontoso-SQL' is currently not available in location 'eastus2' zones '' for subscription '2be16060-ff3f-43b7-90b2-9f5c7b76d746'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'.","details":[{"code":"SkuNotAvailable","message":"The resource with id: '/subscriptions/2be16060-ff3f-43b7-90b2-9f5c7b76d746/resourceGroups/synapseworkshop/providers/Microsoft.Compute/virtualMachines/sricontoso-SQL' failed validation with message: 'The requested size for resource '/subscriptions/2be16060-ff3f-43b7-90b2-9f5c7b76d746/resourceGroups/synapseworkshop/providers/Microsoft.Compute/virtualMachines/sricontoso-SQL' is currently not available in location 'eastus2' zones '' for subscription '2be16060-ff3f-43b7-90b2-9f5c7b76d746'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'."}]},{"code":"InvalidTemplateDeployment","message":"The template deployment failed with error: 'The resource with id: '/subscriptions/2be16060-ff3f-43b7-90b2-9f5c7b76d746/resourceGroups/synapseworkshop/providers/Microsoft.Compute/virtualMachines/sricontoso-File' failed validation with message: 'The requested size for resource '/subscriptions/2be16060-ff3f-43b7-90b2-9f5c7b76d746/resourceGroups/synapseworkshop/providers/Microsoft.Compute/virtualMachines/sricontoso-File' is currently not available in location 'eastus2' zones '' for subscription '2be16060-ff3f-43b7-90b2-9f5c7b76d746'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'.","details":[{"code":"SkuNotAvailable","message":"The resource with id: '/subscriptions/2be16060-ff3f-43b7-90b2-9f5c7b76d746/resourceGroups/synapseworkshop/providers/Microsoft.Compute/virtualMachines/sricontoso-File' failed validation with message: 'The requested size for resource '/subscriptions/2be16060-ff3f-43b7-90b2-9f5c7b76d746/resourceGroups/synapseworkshop/providers/Microsoft.Compute/virtualMachines/sricontoso-File' is currently not available in location 'eastus2' zones '' for subscription '2be16060-ff3f-43b7-90b2-9f5c7b76d746'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'."}]}],"message":"Multiple error occurred: BadRequest,BadRequest. Please see details."}

**Comment by cbattlegear** [comment]
Based on the error, please try a different region, I presume eastus2 is currently having issues with the dev test quota.
